version: '0.1'
services:
  web:
    build: 
        context: .
        dockerfile: Dockerfile
    ports: 
        - 80:80
    volumes:
       - C:\Users\Usuario\AppData\Roaming\Microsoft\UserSecrets:/root/.microsoft/usersecrets:ro
       - ./backend:/app
       - ../:/src/

    depends_on:
        - db
        
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local